### ISSUE TITLE
Redundant contributors files

### ISSUE THREAD

**Issue by erjank** [mse150s20/p2-kinetics#27]
We need to pick either "contributors" or "contributors.txt" and stick with it for the people who are helping out!

**Comment by ashtonenrriques** [comment]
I think contributors.txt is fine but wouldn't feel comfortable deleting the other one

**Comment by erjank** [comment]
Who will be the hero that copies the names from `contributors` and puts them into `contributors.txt` before `git rm contributors`?

**Comment by erjank** [comment]
Ashton and Hayes did it, but Eric stole the attention in class. WHAT  A JERK.
