### ISSUE TITLE
Finding Group

### ISSUE THREAD

**Issue by sampiraino** [mse150s20/p2-kinetics#32]
Add CSV file of date/infections for the state of Idaho

**Comment by jennyfothergill** [comment]
Sam, I'm going to reopen this because it's a good one :)

**Comment by sampiraino** [comment]
I've found a good simple data source for current csv dates and infections. It is the New York Times GitHub Repo:
https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv

data includes all states, and extra data(deaths) so it would need a program to sort through it
I'm not sure how to continue

**Comment by jennyfothergill** [comment]
Nice! This data looks good, and how convenient to find a csv ready to go! Recall that project 1 required you to read in and sort through a csv. Try writing a script that reads in this csv. The difference here is you'll be working with strings, which numpy doesn't handle by default. You could try using [numpy's dtype function to tell the reader how to parse the data](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.html) or you could try [the csv module](https://stackoverflow.com/a/17933417) or you could try using [pandas](https://stackoverflow.com/a/17942117).

**Comment by erjank** [comment]
Addressed in ashton's PR #35
