### ISSUE TITLE
Variable names are not descriptive

### ISSUE THREAD

**Issue by erjank** [mse150s20/p2-kinetics#5]
The variable names (A, B, C, etc) in kinetics.py need to be updated to give us more information for the coronavirus kinetics modeling we're doing.

**Comment by shannoncrain** [comment]
To whoever commented in kinetics.py: why not just rename A, B, and C? It's better in the long run.

Also, k1, k2, and k3 in the dead file need better variable names.

**Comment by jennyfothergill** [comment]
fixed by #118 👍
