### ISSUE TITLE
Add day that the quarantine started 

### ISSUE THREAD

**Issue by jennyfothergill** [mse150s20/p2-kinetics#56]
What day did the governor issued stay at home order?
What day did BSU go to online?
What day are these vs. the day of the first infection?

**Comment by ashtonenrriques** [comment]
Added "additional information" column to idaho_infections.csv" and marked those dates

**Comment by sampiraino** [comment]
Added text file Data/ID_Background_Info.txt with important dates

**Comment by jennyfothergill** [comment]
Awesome!-- I think this issue is resolved.
