### ISSUE TITLE
Idaho infection and death data missing.

### ISSUE THREAD

**Issue by erjank** [mse150s20/p2-kinetics#7]
In order to initialize our models and to measure the accuracy of our models, we need to know how many people in Idaho have been infected by coronavirus, and on which days these infections were reported.

**Comment by erjank** [comment]
To fulfill this issue, let's create a csv file that has dates in one column and infections in the other columns. As a simplest case this can be infections throughout the state, but individual columns with counties or cities would be even better!

**Comment by ashtonenrriques** [comment]
file created, looking for accurate data

**Comment by ashtonenrriques** [comment]
Can only find day by day data for entire state, counties seem to just report to the state without publishing publicly

**Comment by erjank** [comment]
Addressed by PR #35
